name: Trigger Netlify Build
on:
  workflow_dispatch:
  # schedule:
    #  17:00 UTC is Noon
    # “At 12:02 PM in December.”
#     - cron: "2 17 * 12 *"
jobs:
  build:
    name: Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
        run: |
          curl --header "X-Advent-Server-Secret: $SERVER_SECRET" $SERVER_URL
